#!/usr/bin/env Rscript
# decontam_analysis.R - Remove contaminants using decontam package

suppressPackageStartupMessages({
  library(decontam)
  library(phyloseq)
  library(tidyverse)
})

show_help <- function() {
  cat("
  decontam_analysis.R - Remove contaminants from microbiome data using decontam package

  Usage:
    Rscript decontam_analysis.R [OPTIONS] SAMPLES_PREFIX NEGATIVES_PREFIX

  Arguments:
    SAMPLES_PREFIX    Path prefix for sample data files (creates <prefix>.counts.tsv, <prefix>.taxonomy.tsv)
    NEGATIVES_PREFIX  Path prefix for negative control data files

  Options:
    -o, --output PREFIX   Output file prefix (default: 'decontaminated')
    -h, --help            Show this help message and exit

  Description:
    This script identifies and removes contaminant taxa from microbiome data using the
    decontam R package. It requires count and taxonomy tables generated by create_trees.py.

  Input files (for both samples and negatives):
    <prefix>.counts.tsv    - OTU count table (OTU_ID x samples)
    <prefix>.taxonomy.tsv  - Taxonomy table (OTU_ID x taxonomy)

  Output files:
    <output>_contaminants.tsv - List of contaminant OTUs
    <output>_counts.tsv       - Filtered OTU count table
    <output>_taxonomy.tsv     - Filtered taxonomy table
    <output>_summary.tsv      - Summary statistics

  Example:
    Rscript decontam_analysis.R /path/to/samples/out /path/to/negatives/out -o decontaminated

    This will process:
      - /path/to/samples/out.counts.tsv and /path/to/samples/out.taxonomy.tsv
      - /path/to/negatives/out.counts.tsv and /path/to/negatives/out.taxonomy.tsv
    and produce output files prefixed with 'decontaminated_'.

  Dependencies:
    decontam, phyloseq, tidyverse R packages
")
}

# Parse arguments
args <- commandArgs(trailingOnly = TRUE)
if (length(args) < 2) {
  stop("Usage: Rscript decontam_analysis.R <samples_prefix> <negatives_prefix> [output_prefix]", 
       call. = FALSE)
}

samples_prefix <- args[1]
negatives_prefix <- args[2]
output_prefix <- ifelse(length(args) > 2, args[3], "decontaminated")

# Function to read decontam-format tables
read_decontam_tables <- function(prefix) {
  counts_file <- paste0(prefix, ".counts.tsv")
  taxonomy_file <- paste0(prefix, ".taxonomy.tsv")
  
  if (!file.exists(counts_file) || !file.exists(taxonomy_file)) {
    stop(paste("Required files not found for prefix:", prefix), call. = FALSE)
  }
  
  counts <- read_tsv(counts_file, show_col_types = FALSE) %>%
    column_to_rownames("OTU_ID")
  
  taxonomy <- read_tsv(taxonomy_file, show_col_types = FALSE) %>%
    column_to_rownames("OTU_ID")
  
  return(list(counts = counts, taxonomy = taxonomy))
}

# Read data
cat("Reading sample data...\n")
samples_data <- read_decontam_tables(samples_prefix)
negatives_data <- read_decontam_tables(negatives_prefix)

# Create phyloseq objects
otu_mat <- as.matrix(samples_data$counts)
tax_mat <- as.matrix(samples_data$taxonomy)

# Create sample metadata
samples <- colnames(otu_mat)
negatives <- colnames(as.matrix(negatives_data$counts))
sample_data_df <- data.frame(
  row.names = samples,
  is.neg = samples %in% negatives
)

ps <- phyloseq(
  otu_table(otu_mat, taxa_are_rows = TRUE),
  tax_table(tax_mat),
  sample_data(sample_data_df)
)

# Identify contaminants using prevalence method
cat("Identifying contaminants...\n")
contam_df <- isContaminant(ps, method = "prevalence", neg = "is.neg")
contam_taxa <- rownames(contam_df)[contam_df$contaminant]

cat(paste("Found", sum(contam_df$contaminant), "contaminant taxa out of", ntaxa(ps), "total.\n"))

# Remove contaminants
ps_noncontam <- prune_taxa(!contam_df$contaminant, ps)

# Save results
cat("Saving results...\n")

# Save contaminant list
write_tsv(
  contam_df %>% rownames_to_column("OTU_ID") %>% filter(contaminant),
  paste0(output_prefix, "_contaminants.tsv")
)

# Save non-contaminant OTU table
noncontam_counts <- as.data.frame(otu_table(ps_noncontam)) %>%
  rownames_to_column("OTU_ID")
write_tsv(noncontam_counts, paste0(output_prefix, "_counts.tsv"))

# Save non-contaminant taxonomy
noncontam_tax <- as.data.frame(tax_table(ps_noncontam)) %>%
  rownames_to_column("OTU_ID")
write_tsv(noncontam_tax, paste0(output_prefix, "_taxonomy.tsv"))

# Summary statistics
summary_df <- data.frame(
  Total_OTUs = ntaxa(ps),
  Contaminants = sum(contam_df$contaminant),
  Non_contaminants = ntaxa(ps_noncontam),
  Percent_contaminated = round(sum(contam_df$contaminant) / ntaxa(ps) * 100, 2)
)
write_tsv(summary_df, paste0(output_prefix, "_summary.tsv"))

cat("Done! Decontamed files saved with prefix:", output_prefix, "\n")